import java.util.HashMap;
import java.util.Map;

/**
 * Created by thc on 2017/1/19
 */
public class JustDoTest {
    public static void main(String[] args) {
//        StringBuffer sb = new StringBuffer();
//        sb.append("'1',");
//        sb.append("'2'");
//        System.out.println(sb);
//        List<String> list = new ArrayList<>();
//        List<String> list = null;
////        System.out.println(list != null);
//        System.out.println(list.isEmpty());
        Map<String, String[]> params = new HashMap<>();
        String[] fid = {"18332"};
        params.put("fid",fid);

//        String[] category = {"18332"};
//        params.put("category",category);
//        String[] ets = {"18332"};
//        params.put("ets",ets);
//        String[] csys = {"18332"};
//        params.put("csys",csys);
//        String[] cdia = {"18332"};
//        params.put("cdia",cdia);
//        String[] chr = {"18332"};
//        params.put("chr",chr);
//        String[] tea = {"1"};
//        params.put("tea",tea);
//        String[] coffee = {"18332"};
//        params.put("coffee",coffee);
//        String[] smoke = {"18332"};
//        params.put("smoke",smoke);
//        String[] alcohol = {"18332"};
//        params.put("alcohol",alcohol);
//        String[] sport = {"18332"};
//        params.put("sport",sport);
//        String[] medicine = {"18332"};
//        params.put("medicine",medicine);
//        String[] temperature = {"16.6"};
//        params.put("temperature",temperature);
//        String[] fingertip = {"18332"};
//        params.put("fingertip",fingertip);
//        String[] humidity = {"18332"};
//        params.put("humidity",humidity);
//        String[] atmos = {"18332"};
//        params.put("atmos",atmos);
//        String[] rest = {"18332"};
//        params.put("rest",rest);
//        String[] mposture = {"18332"};
//        params.put("mposture",mposture);
//        String[] night_sleep = {"18332"};
//        params.put("night_sleep",night_sleep);
//        String[] noon_sleep = {"18332"};
//        params.put("noon_sleep",noon_sleep);
//        String[] jsyl = {"0"};
//        params.put("jsyl",jsyl);
//        String[] tired = {"18332"};
//        params.put("tired",tired);
//        String[] kynl = {"18332"};
//        params.put("kynl",kynl);
//        String[] ylzs = {"18332"};
//        params.put("ylzs",ylzs);
//        String[] hage = {"18332"};
//        params.put("hage",hage);
//        String[] relax = {"18332"};
//        params.put("relax",relax);
//        String[] maxhr = {"18332"};
//        params.put("maxhr",maxhr);
//        String[] minhr = {"18332"};
//        params.put("minhr",minhr);
//        String[] isnormal = {"18332"};
//        params.put("isnormal",isnormal);
//        String[] dxxl = {"18332"};
//        params.put("dxxl",dxxl);
//        String[] xlbq = {"18332"};
//        params.put("xlbq",xlbq);
//        String[] xdgh = {"18332"};
//        params.put("xdgh",xdgh);
//        String[] hr = {"18332"};
//        params.put("hr",hr);
//        String[] syncsys = {"18332"};
//        params.put("syncsys",syncsys);
//        String[] syncdia = {"18332"};
//        params.put("syncdia",syncdia);
//        String[] ppt0 = {"18332"};
//        params.put("ppt0",ppt0);
//        String[] nloginname1 = {"test1"};
//        params.put("nloginname1",nloginname1);
//        String[] ncsys1 = {"110"};
//        params.put("ncsys1",ncsys1);
//        String[] ncdia1 = {"18332"};
//        params.put("ncdia1",ncdia1);
//        String[] nloginname2 = {"18332"};
//        params.put("nloginname2",nloginname2);
//        String[] ncsys2 = {"110"};
//        params.put("ncsys2",ncsys2);
//        String[] ncdia2 = {"18332"};
//        params.put("ncdia2",ncdia2);
//        String[] label = {"18332"};
//        params.put("label",label);
//        String[] phone = {"SZJ-11"};
//        params.put("phone",phone);
//        String[] watch = {"18332"};
//        params.put("watch",watch);
//        String[] mercury = {"18332"};
//        params.put("mercury",mercury);
//        String[] stethosope = {"18332"};
//        params.put("stethosope",stethosope);
//
//        Long _fid = Long.parseLong(params.getOrDefault("fid", defaul0)[0]);
//        String _category = params.getOrDefault("category", defaultempty)[0];
//        Long _duration = Long.parseLong(params.getOrDefault("ets", defaul0)[0]) - Long.parseLong(params.getOrDefault("sts", defaul0)[0]);
//        int _csys = Integer.parseInt(params.getOrDefault("csys", defaul0)[0]);
//        int _cdia = Integer.parseInt(params.getOrDefault("cdia", defaul0)[0]);
//        int _chr = Integer.parseInt(params.getOrDefault("chr", defaul0)[0]);
//        int _tea = Integer.parseInt(params.getOrDefault("tea", defaul0)[0]);
//        int _coffee = Integer.parseInt(params.getOrDefault("coffee", defaul0)[0]);
//        int _smoke = Integer.parseInt(params.getOrDefault("smoke", defaul0)[0]);
//        int _alcohol = Integer.parseInt(params.getOrDefault("alcohol", defaul0)[0]);
//        int _sport = Integer.parseInt(params.getOrDefault("sport", defaul0)[0]);
//        String _medicine = params.getOrDefault("medicine", defaultempty)[0];
//        Float _temperature = Float.parseFloat(params.getOrDefault("temperature", defaul0)[0]);
//        Float _fingertip = Float.parseFloat(params.getOrDefault("fingertip", defaul0)[0]);
//        Float _humidity = Float.parseFloat(params.getOrDefault("humidity", defaul0)[0]);
//        Float _atmos = Float.parseFloat(params.getOrDefault("atmos", defaul0)[0]);
//        int _rest = Integer.parseInt(params.getOrDefault("rest", defaul0)[0]);
//        int _mposture = Integer.parseInt(params.getOrDefault("mposture", defaul0)[0]);
//        int _night_sleep = Integer.parseInt(params.getOrDefault("night_sleep", defaul0)[0]);
//        int _noon_sleep = Integer.parseInt(params.getOrDefault("noon_sleep", defaul0)[0]);
//        int _jsyl = Integer.parseInt(params.getOrDefault("jsyl", defaul0)[0]);
//        int _tired = Integer.parseInt(params.getOrDefault("tired", defaul0)[0]);
//        int _kynl = Integer.parseInt(params.getOrDefault("kynl", defaul0)[0]);
//        int _ylzs = Integer.parseInt(params.getOrDefault("ylzs", defaul0)[0]);
//        int _hage = Integer.parseInt(params.getOrDefault("hage", defaul0)[0]);
//        int _relax = Integer.parseInt(params.getOrDefault("relax", defaul0)[0]);
//        int _maxhr = Integer.parseInt(params.getOrDefault("maxhr", defaul0)[0]);
//        int _minhr = Integer.parseInt(params.getOrDefault("minhr", defaul0)[0]);
//        int _isnormal = Integer.parseInt(params.getOrDefault("isnormal", defaul0)[0]);
//        int _dxxl = Integer.parseInt(params.getOrDefault("dxxl", defaul0)[0]);
//        int _xlbq = Integer.parseInt(params.getOrDefault("xlbq", defaul0)[0]);
//        int _xdgs = Integer.parseInt(params.getOrDefault("xdgs", defaul0)[0]);
//        int _xdgh = Integer.parseInt(params.getOrDefault("xdgh", defaul0)[0]);
//        int _hr = Integer.parseInt(params.getOrDefault("hr", defaul0)[0]);
//        int _syncsys = Integer.parseInt(params.getOrDefault("syncsys", defaul0)[0]);
//        int _syncdia = Integer.parseInt(params.getOrDefault("syncdia", defaul0)[0]);
//        int _ppt0 = Integer.parseInt(params.getOrDefault("ppt0", defaul0)[0]);
//
//        String _nloginname1 = params.getOrDefault("nloginname1", defaultempty)[0];
//        int _ncsys1 = Integer.parseInt(params.getOrDefault("ncsys1", defaul0)[0]);
//        int _ncdia1 = Integer.parseInt(params.getOrDefault("ncdia1", defaul0)[0]);
//        String _nloginname2 = params.getOrDefault("nloginname2", defaultempty)[0];
//        int _ncsys2 = Integer.parseInt(params.getOrDefault("ncsys2", defaul0)[0]);
//        int _ncdia2 = Integer.parseInt(params.getOrDefault("ncdia2", defaul0)[0]);
//        String _label = params.getOrDefault("label", defaultempty)[0];
//        String _phone = params.getOrDefault("phone", defaultempty)[0];
//        String _watch = params.getOrDefault("watch", defaultempty)[0];
//        String _mercury = params.getOrDefault("mercury", defaultempty)[0];
//        String _stethoscope = params.getOrDefault("stethoscope", defaultempty)[0];
    }

    protected static final String[] defaul0 = {"0"};
    protected static final String[] defaultempty = {""};
}
